### ISSUE TITLE
Need to wait for score confirmation

### ISSUE THREAD

**Issue by TristanDebrunner** [AtlatntisSports/uwh-refbox-rs#34]
The tournament manager doesn't wait for confirmation of score at the potential end of a game. It should ask for score confirmation at the end of any period that could be the end of the game.

**Comment by TristanDebrunner** [comment]
Outstanding question:
Does the clock keep running while this happens? For example, imagine second half ends, and it takes the refs `N` seconds to confirm that the score is tied. Should the pre overtime period be started with `pre_overtime_duration` seconds left, or `pre_overtime_duration - N`?

If we could guarantee that `N` is small, I would say we should use `pre_overtime_duration - N`, but what if `pre_overtime_duration < N`?

I see two main options:
1. After some timeout (ie `pre_overtime_duration/2`, or just 20s) we dismiss the confirmation page automatically, assuming that the score is correct. If "NO" is pressed, we wait for the correct score to be input, in which we are making the assumption that the refs are paying attention and will input the score promptly. We then use `pre_overtime_duration - N`. This is admittedly somewhat strange behavior, but it does allow the program to auto advance if the deck ref ignores it.

2. We use `pre_overtime_duration`, and impress upon users the importance of a prompt response. My main objection to this is that the program is stuck if the user ignores it, while the rest of the program is structured to automatically advance through everything.

**Comment by estraily-navisjon** [comment]
I like your first option. I think that it is likely the time/score keeper will be paying attention and if not then it just moves on. If they screw it up then the scores can be manually changed on uwhscores.com. The trickier situation is in the event of a goal close to end of game and it doesn't get input in time, then what do we do to get to the same game state so that overtime can commence?

**Comment by TristanDebrunner** [comment]
I'm not sure what you're asking about there. Do you mean if there's a goal that doesn't get put in, and then the confirmation disappears before the tying goal is entered?

If so, I don't think there's much we can do. If the refs aren't paying attention, and miss the confirmation, there's not really an easy way to allow them to recover, and at that point I think it's fair to chalk up to extreme user error and say we won't deal with it.

**Comment by ericstraily** [comment]
what about a button that shows up after a game that says something like "Edit last game score" or something?

**Comment by TristanDebrunner** [comment]
And then it switches back to overtime if appropriate? The logic to make that happen is fairly complicated, and technically there's already a workaround. The refs just start over the game in question, edit the time to skip to the end of second half (or wherever they screwed up), and when the confirmation pops up again, they don't screw it up that time.

**Comment by ericstraily** [comment]
That works for me.

Do you still have any questions about this topic then or are we good?
